import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await page.goto('http://localhost:5174/');
await page.waitForTimeout(2000);
await page.screenshot({ path: '/tmp/hero-desktop.png', fullPage: false });
await page.screenshot({ path: '/tmp/full-desktop.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: '/tmp/hero-mobile.png', fullPage: false });
await browser.close();
console.log('done');
